web2_forum/models/topic.py
import time

from sqlalchemy import (
    String,
    Integer,
    Column,
    Text,
    UnicodeText,
    Unicode,
)

from models import Model
from models.base_model import (
    SQLMixin,
    db,
)
from models.board import Board
from models.user import User
from models.reply import Reply
from utils import log


class Topic(SQLMixin, db.Model):
    view = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False)

    @classmethod
    def new(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.view += 1
        log('get m', m)
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count =len(self.replies())
        return count

    def board(self):
        b = Board.one(id=self.board_id)
        return b

web2_forum/routes/reply.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.reply import Reply
from utils import log

main = Blueprint('reply', __name__)


@main.route('/add', methods=['POST'])
def add():
    form = request.form.to_dict()
    u = current_user()
    # log('DEBUG', form)
    m = Reply.add(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

web2_forum/routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.topic import Topic
from models.board import Board
from routes.helper import (
    csrf_required,
    new_csrf_token,
    login_required,
    csrf_tokens,
)
from utils import log

main = Blueprint('topic', __name__)


@main.route('/')
def index():
    board_id = int(request.args.get('board_id', -1))
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    return render_template('topic/index.html', ms=ms, token=token, bs=bs, bid=board_id)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    log('detail', m)
    return render_template('topic/detail.html', topic=m)


@main.route('delete')
@csrf_required
@login_required
def delete():
    u = current_user()
    id = int(request.args['id'])
    log('delete topic user is', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route('/add', methods=['POST'])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))


@main.route('/new')
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    token = new_csrf_token()
    return render_template('topic/new.html', bs=bs, token=token, bid=board_id)

web2_forum/templates/topic/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club test</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
<!--    <link href="//cdn.bootcss.com/prism/1.8.0/themes/prism.css" rel="stylesheet">-->
</head>
<body>
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 {{ topic.created_time | format_time }}
            </span>
                    <span>
                <a href="../profile.html"> 作者 {{ topic.user().username }}</a>
                {# 作者 {{ User.one(id=topic.user_id).username }} #}
        	</span>
                    <span>
          	    {{ topic.view }} 次浏览
        	</span>
                    <span>
                来自 {{ topic.board().title }}
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content }}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        {# for i, r in enumerate(topic.replies())  #}
            {% set u = r.user() %}
            <div class='cell reply_area reply_item'>
                <div class='user_info'>
                    <a class='dark reply_author'>
                        {{ u.username }}
                    </a>
                    <a class="reply_time">
                        {{ loop.index }}楼 / {{ loop.length }}楼 •
                        <span >{{ r.created_time | format_time }}</span>
                    </a>
                </div>
                <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">{{ r.content | safe | remove_script }}</div>
                        {# <div class="markdown-text">{{ r.content }}</div> #}
                </div>
            </div>
        {% endfor %}
    </div>
    <div>
        <form action="{{ url_for('reply.add') }}" method="post">
            <input type="hidden" name="topic_id" value="{{ topic.id }}">
            <textarea name="content"></textarea>
            <button>添加回复</button>
        </form>
    </div>
</div>
<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
{#<scirp src="xxx.js"></scirp>#}
<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        // markdown -> html 的处理放在高亮前面
        // 因为高亮是针对 html 格式的
        // lang -> language 不需要转 prism 自动转了
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function () {
        // 自动加载对应的语言 不然要手动加入各个语言的 js
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var __main = function () {
        markContents()
        highlight()
    }

    __main()

</script>
</body>
</html>

web2_forum/templates/topic/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
<!--    <link rel="stylesheet" href="/static/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="/static/css/style.css">
<!--    <link rel="stylesheet" href="/static/css/index.min.23a5b1ca.min.css" media="all">-->
    <!--<link rel="stylesheet" href="/static/lib/editor/editor.css">-->
    <!--<link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">-->
    <!--<script src="/static/lib/jquery-3.0.0.min.js"></script>-->
    <!--<script src="/static/lib/markdownit.js"></script>-->
    <!--<script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>-->
    <!--<script src="/static/lib/editor/editor.js"></script>-->
    <!--<script src="/static/lib/editor/ext.js"></script>-->
</head>
<body>

    <div id="main">
        <div id="sidebar">
            <div class="panel">

    <div class="header">
      <span class="col_fade">个人信息</span>
    </div>
    <div class="inner">
      <div class="user_card">
  <div>
    <a class="user_avatar" >
      <img src="/static/doge.gif" title="Rolling-meatballs">
    </a>
    <span class="user_name"><a class="dark"> {{ username }} </a></span>

    <div class="board clearfix">
      <div class="floor">
{#        <span class="big">积分: 10 </span>#}
      </div>
    </div>
    <div class="space clearfix"></div>
    <span class="signature">
        “

            这家伙很懒，什么个性签名都没有留下。

        ”
    </span>
  </div>
</div>





    </div>

  </div>

            <div class="panel">
                <div class="inner">
<!--                    <a href="{{ url_for('topic.add') }}" class="create_topic_btn">-->
                    <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                        <span class="span-success">发布话题</span>
                    </a>
                </div>
            </div>
        </div>
        <div id="content">
            <div class="panel">
                <div class="header">
                    <a href="/topic"
                   class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
                <div class="inner post">
                    <div class="topic_list">
                        {% for t in ms %}
                        <div class="cell">
                            <div class="topic_title_wrapper">
                                <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                    {{ t.title }}
                                </a>
                                <span>{{ t.replies() | count }} / {{ t.view }}</span>
<!--                                {# count(t.replies()) #}-->
<!--{#                                 <span>{{ t.reply_count() }} / {{ t.views }}</span>#}-->
<!--                                {#len(Reply.all(topic_id=t.id))#}-->
                                <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                删除
                                </a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
<!--<script src="/static/js/test.js"></script>-->
</html>

web2_forum/templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
<!--    <link rel="stylesheet" href="/static/lib/editor/editor.css">-->
<!--    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">-->
<!--    <script src="/static/lib/jquery-3.0.0.min.js"></script>-->
<!--    <script src="/static/lib/markdownit.js"></script>-->
<!--    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>-->
<!--    <script src="/static/lib/editor/editor.js"></script>-->
<!--    <script src="/static/lib/editor/ext.js"></script>-->
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
{#<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">#}
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <span class="tab-selector">选择版块：</span>
        <select name="board_id" id="board" required>
            {% for b in bs %}
                {% if bid == b.id %}
                    <option value="{{ b.id }}" selected >{{ b.title }}</option>
                {% else %}
                    <option value="{{ b.id }}" >{{ b.title }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>